name: Test workflows

on:
  # workflow_dispatch:
  pull_request_target:
    types: [opened, synchronize]

env:
  DEVELOPER_DIR: /Applications/Xcode_14.0.1.app/Contents/Developer

jobs:
  withPermission:
    runs-on: ubuntu-latest
    name: An example job to comment a PR
    permissions:
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: test echo
        run: echo ${{ secrets.AWS_ACCESS_KEY_ID }}

      - name: Publish links to apps for download
        run: |
          gh pr comment --body \
          "| android :robot:  | iOS :apple: | 
          | ------------- | ------------- |
          | HAHA MY LINK  | https://ios.with.pl  |"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  withoutPermission:
    runs-on: ubuntu-latest
    name: An example job to comment a PR
    steps:
      - name: Checkout
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: test echo
        run: echo ${{ secrets.AWS_ACCESS_KEY_ID }}

      - name: Publish links to apps for download
        run: |
          gh pr comment --body \
          "| android :robot:  | iOS :apple: | 
          | ------------- | ------------- |
          | HAHA MY LINK  | https://ios.without.pl  |"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
